---
language: python
python: "2.7"

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Update apt
  - sudo apt-get -qq update

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the playbook with ansible-playbook
  - sudo ansible-playbook tests/test.yml -i tests/inventory

  # Check the DockbarX is configured
  - "gconftool-2 --get /apps/dockbarx/launchers | grep 'test-app;/usr/share/applications/test-app.desktop'"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
